spring:
  application:
    name: geteway
eureka:
  client:
    service-url:
      default-zone: "http/localhost:8761/eureka/"
    enabled: true
    registry-fetch-interval-seconds:  10
    instance-info-replication-interval-seconds: 20
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

server:
  port: 9090
